sudo: required
language: python
dist: xenial
python: "3.7"

branches:
  only:
    - master

env:
  - ANSIBLE_VERSION=latest

install:
  - pip3 install ansible ansible-lint

script:
  # Basic Ansible syntax check
  - ansible-playbook -i "127.0.0.1," macOS/ansible/main.yml --syntax-check
  # Ansible-lint, excluding shell command warning
  - ansible-lint -x 305 macOS/ansible/main.yml
